import { existsSync, readFileSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { resolve } from "node:path";
import { getStringFlag, hasFlag, parseArgs } from "../git/subtree-args";
import { loadConfig, ReadmeTargetConfig } from "./config";
import { findRepoRoot } from "../git/repo";

type ResolvedReadmeTarget = {
  targetName: string;
  packagePath: string;
  outputPath: string;
  binPath: string;
  binCommand: string;
  helpCommands?: string[];
  includeCommands: string[];
  excludeCommands: string[];
};

function parseArgsList(input: string): string[] {
  return input
    .trim()
    .split(/\s+/)
    .map((part) => part.trim())
    .filter(Boolean);
}

function captureHelp(binPath: string, args: string[], cwd: string): string {
  const result = spawnSync(process.execPath, [binPath, ...args], {
    cwd,
    env: process.env,
    encoding: "utf8",
    stdio: "pipe",
    maxBuffer: 1024 * 1024 * 20,
  });

  if (result.status !== 0) {
    throw new Error(`Failed to capture help for: ${args.join(" ") || "--help"}`);
  }

  return (result.stdout ?? "").trimEnd();
}

function parseTopLevelCommands(helpOutput: string): string[] {
  const lines = helpOutput.split(/\r?\n/);
  const commands: string[] = [];
  let inCommands = false;

  for (const rawLine of lines) {
    const line = rawLine.replace(/\t/g, "    ");
    if (!inCommands) {
      if (line.trim() === "Commands:") inCommands = true;
      continue;
    }

    if (line.trim() === "" && commands.length > 0) break;
    if (line.trim() === "") continue;
    if (!line.startsWith(" ")) break;

    const match = line.match(/^\s{2,}([a-z0-9-]+)\s{2,}/i);
    if (!match) continue;
    const command = match[1];
    if (command) commands.push(command);
  }

  return Array.from(new Set(commands));
}

function resolveTargetFromConfig(
  repoRoot: string,
  targetName: string,
  configTarget: ReadmeTargetConfig,
): ResolvedReadmeTarget {
  const packagePath = configTarget.packagePath;
  const packageJsonPath = resolve(repoRoot, packagePath, "package.json");

  if (!existsSync(packageJsonPath)) {
    throw new Error(`Missing package.json for readme target '${targetName}': ${packageJsonPath}`);
  }

  const outputPath = resolve(repoRoot, packagePath, configTarget.output ?? "README.md");

  let binPath = configTarget.binPath ? resolve(repoRoot, configTarget.binPath) : "";
  let binCommand = configTarget.bin ?? "";

  if (!binPath || !binCommand) {
    const pkg = JSON.parse(readFileSync(packageJsonPath, "utf8")) as {
      bin?: string | Record<string, string>;
      name?: string;
    };

    if (!binPath) {
      if (typeof pkg.bin === "string") {
        binPath = resolve(repoRoot, packagePath, pkg.bin);
      } else if (pkg.bin && typeof pkg.bin === "object") {
        const first = Object.values(pkg.bin)[0];
        if (first) binPath = resolve(repoRoot, packagePath, first);
      }
    }

    if (!binCommand) {
      if (typeof pkg.bin === "string") {
        binCommand = pkg.name ? pkg.name.split("/").pop() ?? "cli" : "cli";
      } else if (pkg.bin && typeof pkg.bin === "object") {
        const firstKey = Object.keys(pkg.bin)[0];
        if (firstKey) binCommand = firstKey;
      }
    }
  }

  if (!binPath || !existsSync(binPath)) {
    throw new Error(`Could not resolve built CLI binary for target '${targetName}'.`);
  }

  if (!binCommand) {
    throw new Error(`Could not resolve CLI command name for target '${targetName}'.`);
  }

  return {
    targetName,
    packagePath,
    outputPath,
    binPath,
    binCommand,
    helpCommands: configTarget.helpCommands,
    includeCommands: configTarget.includeCommands ?? [],
    excludeCommands: configTarget.excludeCommands ?? [],
  };
}

async function resolveTarget(targetName: string): Promise<ResolvedReadmeTarget> {
  const repoRoot = findRepoRoot(process.cwd());
  const config = await loadConfig(repoRoot);
  const targets = config.readme?.targets ?? {};

  if (targets[targetName]) {
    return resolveTargetFromConfig(repoRoot, targetName, targets[targetName]);
  }

  if (targetName === "cli") {
    return resolveTargetFromConfig(repoRoot, "cli", { packagePath: "packages/cli", bin: "lally" });
  }

  throw new Error(`Unknown readme target: ${targetName}`);
}

function buildReadme(params: {
  packageName: string;
  generatorCommand: string;
  sections: Array<{ heading: string; content: string }>;
}): string {
  const sectionMarkdown = params.sections
    .map((section) => `### \`${section.heading}\`\n\n\`\`\`text\n${section.content}\n\`\`\``)
    .join("\n\n");

  return `# ${params.packageName}

CLI for \`${params.packageName}\`.

> This README is auto-generated by \`${params.generatorCommand}\`.

## Install

\`\`\`bash
pnpm add -D ${params.packageName}
\`\`\`

or run with \`pnpm dlx\`:

\`\`\`bash
pnpm dlx ${params.packageName}@alpha --help
\`\`\`

${sectionMarkdown}

## License

MIT. See \`LICENSE\`.
`;
}

export async function runRepoReadmeCommand(args: string[]): Promise<number> {
  const { flags } = parseArgs(["readme", ...args]);
  const targetFromFlag = getStringFlag(flags, "target");
  const positional = args.find((arg) => !arg.startsWith("--"));
  const target = (targetFromFlag ?? positional ?? "cli").trim();

  const resolved = await resolveTarget(target);
  const repoRoot = findRepoRoot(process.cwd());

  const packageJsonPath = resolve(repoRoot, resolved.packagePath, "package.json");
  const pkg = JSON.parse(await readFile(packageJsonPath, "utf8")) as { name?: string };
  const packageName = pkg.name ?? resolved.binCommand;

  const rootHelp = captureHelp(resolved.binPath, ["--help"], repoRoot);

  const commands = (() => {
    if (resolved.helpCommands && resolved.helpCommands.length > 0) {
      return resolved.helpCommands.map((entry) => parseArgsList(entry).join(" "));
    }

    const auto = parseTopLevelCommands(rootHelp);
    const included = [...auto, ...resolved.includeCommands];
    return Array.from(new Set(included)).filter((name) => !resolved.excludeCommands.includes(name));
  })();

  const sections: Array<{ heading: string; content: string }> = [
    { heading: `${resolved.binCommand} --help`, content: rootHelp },
  ];

  for (const command of commands) {
    const trimmed = command.trim();
    if (!trimmed) continue;

    const help = captureHelp(resolved.binPath, [...parseArgsList(trimmed), "--help"], repoRoot);
    sections.push({ heading: `${resolved.binCommand} ${trimmed} --help`, content: help });
  }

  const generatorCommand = `lally repo readme --target ${resolved.targetName}`;
  const content = buildReadme({ packageName, generatorCommand, sections });

  const check = hasFlag(flags, "check");
  const print = hasFlag(flags, "print");

  if (check) {
    const current = await readFile(resolved.outputPath, "utf8");
    if (current === content) {
      console.log("README is up to date.");
      return 0;
    }
    console.error(`README is out of date: ${resolved.outputPath}`);
    console.error(`Run: lally repo readme --target ${resolved.targetName}`);
    return 1;
  }

  await writeFile(resolved.outputPath, content, "utf8");
  console.log(`Generated ${resolved.outputPath}`);

  if (print) {
    console.log("\n---\n");
    console.log(content);
  }

  return 0;
}
